### ISSUE TITLE
are macros necessary?

### ISSUE THREAD

**Issue by madvas** [district0x/cljs-ipfs-native#2]
If it's native now, is doing it via macros necessary? cannot be it just regular functions? 
If can, please remake into normal function definitions

**Comment by madvas** [comment]
ok cool

**Comment by wambat** [comment]
I could not find an existing way to autogenerate macroexpanded version: the only way i see it possible is to add souces/macroexpanding handling to https://github.com/weavejester/codox.
Meanwhile, i've generated docs https://district0x.github.io/cljs-ipfs-native/

Anyway, everything what the macro does is creating wrappers like this:
```
(clojure.core/defn add
  ([data]
   (add data nil))
  ([data callback]
   (add data nil callback))
  ([data options callback]
   (add (clojure.core/deref cljs-ipfs-api.core/*ipfs-instance*) data options callback))
  ([ipfs-inst data options callback]
   (clojure.core/let [callback (wrap-callback callback)]
     (clojure.core/let [args (clojure.core/remove clojure.core/nil? [data])]
       (api-call ipfs-inst "add" args {:data data, :options options, :callback callback})))))```

**Comment by madvas** [comment]
Okay, it's fine as it is then. Thanks for generating docs, that's useful
